<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
    <line>
      <![CDATA[driver--null]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="6736" started-at="2017-11-23T07:07:10Z" finished-at="2017-11-23T07:07:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6736" started-at="2017-11-23T07:07:10Z" finished-at="2017-11-23T07:07:16Z">
      <class name="com.craftsvilla.test.CartC">
        <test-method status="PASS" signature="LaunchApp()[pri:0, instance:com.craftsvilla.test.CartC@66a3ffec]" name="LaunchApp" is-config="true" duration-ms="6697" started-at="2017-11-23T12:37:10Z" finished-at="2017-11-23T12:37:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApp -->
        <test-method status="PASS" signature="testCart()[pri:0, instance:com.craftsvilla.test.CartC@66a3ffec]" name="testCart" duration-ms="6" started-at="2017-11-23T12:37:16Z" finished-at="2017-11-23T12:37:16Z">
          <reporter-output>
            <line>
              <![CDATA[driver--null]]>
            </line>
          </reporter-output>
        </test-method> <!-- testCart -->
        <test-method status="FAIL" signature="closeApp()[pri:0, instance:com.craftsvilla.test.CartC@66a3ffec]" name="closeApp" is-config="true" duration-ms="0" started-at="2017-11-23T12:37:16Z" finished-at="2017-11-23T12:37:16Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at generic.BaseTest.closeApp(BaseTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:731)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.craftsvilla.test.CartC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
